"""initial schema

Revision ID: 510976f9d708
Revises: 
Create Date: 2026-02-09 12:49:10.590891

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '510976f9d708'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('combined_results')
    op.drop_table('user')
    op.drop_table('aneamia_checks')
    op.drop_table('health_record')
    with op.batch_alter_table('anaemia_checks', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('bmi',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('hemoglobin',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('result',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_index(batch_op.f('idx_anaemia_checks_created_at'))
        batch_op.create_index(batch_op.f('ix_anaemia_checks_created_at'), ['created_at'], unique=False)
        batch_op.drop_column('risk_level')
        batch_op.drop_column('symptoms')

    with op.batch_alter_table('combined_checks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('blockchain_hash', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('blockchain_verified', sa.Boolean(), nullable=True))
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('bmi',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('hemoglobin',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('cycle_length',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('overall_risk',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_index(batch_op.f('idx_combined_checks_created_at'))
        batch_op.create_index(batch_op.f('ix_combined_checks_created_at'), ['created_at'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('gender')
        batch_op.drop_column('pcod_risk_level')
        batch_op.drop_column('anemia_risk_level')
        batch_op.drop_column('recommendations')

    with op.batch_alter_table('pcod_checks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cycle_length', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('bleeding_days', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('blockchain_hash', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('blockchain_verified', sa.Boolean(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=False)
        batch_op.alter_column('bmi',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_pcod_checks_created_at'))
        batch_op.create_index(batch_op.f('ix_pcod_checks_created_at'), ['created_at'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_pcod_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('risk_score')
        batch_op.drop_column('symptoms')

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.alter_column('height',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('college',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint(batch_op.f('user_profiles_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_users_created_at'))
        batch_op.drop_constraint(batch_op.f('users_roll_no_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_roll_no'), ['roll_no'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_roll_no'))
        batch_op.drop_index(batch_op.f('ix_users_full_name'))
        batch_op.create_unique_constraint(batch_op.f('users_roll_no_key'), ['roll_no'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_users_created_at'), ['created_at'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_profiles_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('phone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
        batch_op.alter_column('college',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('weight',
               existing_type=sa.String(length=50),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('height',
               existing_type=sa.String(length=50),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('pcod_checks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symptoms', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('risk_score', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_pcod_user'), 'users', ['user_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_pcod_checks_created_at'))
        batch_op.create_index(batch_op.f('idx_pcod_checks_created_at'), ['created_at'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('bmi',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('age',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('blockchain_verified')
        batch_op.drop_column('blockchain_hash')
        batch_op.drop_column('bleeding_days')
        batch_op.drop_column('cycle_length')

    with op.batch_alter_table('combined_checks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recommendations', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('anemia_risk_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pcod_risk_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_combined_checks_created_at'))
        batch_op.create_index(batch_op.f('idx_combined_checks_created_at'), ['created_at'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('overall_risk',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('cycle_length',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('hemoglobin',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('bmi',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('age',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('blockchain_verified')
        batch_op.drop_column('blockchain_hash')
        batch_op.drop_column('result')

    with op.batch_alter_table('anaemia_checks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symptoms', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('risk_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_anaemia_checks_created_at'))
        batch_op.create_index(batch_op.f('idx_anaemia_checks_created_at'), ['created_at'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('result',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('hemoglobin',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('bmi',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('age',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('health_record',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cluster_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('risk_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('blockchain_hash', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('prediction_result', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('health_record_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('health_record_pkey'))
    )
    op.create_table('aneamia_checks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hemoglobin', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bmi', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('symptoms', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('result', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('risk_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('anaemia_checks_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('anaemia_checks_pkey'))
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('roll_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    sa.UniqueConstraint('roll_number', name=op.f('user_roll_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('combined_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('anaemia_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('pcod_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('final_category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('combined_results_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('combined_results_pkey'))
    )
    # ### end Alembic commands ###
